spring.application.name=event-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/event_service
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

wellness.base-url=http://localhost:8085

event-service.version=v1.0

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=event-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.properties.specific.value.type=ca.gbc.comp3095.eventservice.dto.GoalCompletedEvent
spring.kafka.properties.use.latest.version=true

kafka.topics.goal-completed=goal-completed
