spring.application.name=event-service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres_event:5432/event_service
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

wellness.base-url=http://wellness-service:8085

event-service.version=v1.0

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

# Lesson 9.2
# Kafka Consumer Properties
# The address of the Kafka broker used to connect to the Kafka cluster.
spring.kafka.bootstrap-servers=broker:29092
# The unique identifier for the consumer group to which this consumer belongs.
spring.kafka.consumer.group-id=notificationService
# The deserializer class used for deserializing the key of the messages from Kafka.
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Will ensure your consumer starts processing all unprocessed events from the beginning of the topic
spring.kafka.consumer.auto-offset-reset=earliest

# Lesson 10.1 (Corrected Avro Consumer Configuration)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# 1. Use the correct Avro Deserializer delegate class
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer

spring.kafka.consumer.properties.schema.registry.url=http://schema-registry:8081

spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.consumer.properties.specific.value.type=ca.gbc.comp3095.goaltrackingservice.event.GoalCompletedEvent

# Kafka session and timeout properties (These look fine)
spring.kafka.consumer.properties.session.timeout.ms=45000
spring.kafka.consumer.properties.heartbeat.interval.ms=15000
spring.kafka.consumer.properties.request.timeout.ms=60000
spring.kafka.consumer.properties.max.poll.interval.ms=300000






management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.level.org.springframework.kafka=INFO
logging.level.ca.gbc.notificationservice=ERROR
logging.level.org.apache.kafka.clients.consumer=ERROR


