# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p comp3095-assignment-integrated -f docker-compose.yml up -d
#     This command will start the containers in detached mode (-d) without rebuilding the images (if they already exist)
#
#     - docker-compose -p comp3095-assignment-integrated -f docker-compose.yml up -d --build
#     This command force the rebuild of images, even if the images already exist
# ------------------------------------------------

services:

  api-gateway:
    image: api-gateway
    ports:
      - "9000:9000"
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_JSON={"logging":{"level":{"root":"INFO","ca.gbc.apigateway":"DEBUG"}}}:
    container_name: api-gateway
    networks:
      - comp3095_assignment


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "8080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-keycloak
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=none
      - KC_HTTP_ENABLED=true
    command:
      - start-dev
    container_name: keycloak
    depends_on:
      - postgres-keycloak
#      - wellness-service
#      - event-service
#      - goal-tracking-service
    networks:
      - comp3095_assignment


  postgres-keycloak:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - keycloak-data:/var/lib/postgresql/data
#      - ./docker/integrated/postgres/data/keycloak:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    container_name: postgres-keycloak
    networks:
      - comp3095_assignment



  wellness-service:
    ports:
      - "8085:8085"
    build:
      context: ./wellness-service
      dockerfile: ./Dockerfile
    container_name: wellness-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_wellness:5432/wellness_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres_wellness
      - redis
    networks:
      - comp3095_assignment


  postgres_wellness:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres_wellness
    environment:
      POSTGRES_DB: wellness_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./docker/integrated/postgres/postgres_wellness/data:/data/postgres   # mount the database
      - ./docker/integrated/postgres/postgres_wellness/init/init.sql:/docker-entrypoint-initdb.d/init.sql  # mount the init.sql script
    networks:
      - comp3095_assignment


  event-service:
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: ./event-service/Dockerfile
    container_name: event-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_event:5432/event_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres_event:
        condition: service_started
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_started
    networks:
      - comp3095_assignment



  postgres_event:
    image: postgres:latest
    ports:
      - "5433:5432"
    container_name: postgres_event
    environment:
      POSTGRES_DB: event_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - comp3095_assignment


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - comp3095_assignment

  goal-tracking-service:
    build:
      context: .
      dockerfile: ./goal-tracking-service/Dockerfile
    container_name: goal-tracking-service
    ports:
      - "8087:8087"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://rootadmin:password@mongodb:27017/goal-tracking-service?authSource=admin
      WELLNESS_BASE_URL: http://wellness-service:8085
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
      - wellness-service
    networks:
      - comp3095_assignment

  pgpadmin_ass:
    image: dpage/pgadmin4
    container_name: pgadmin_ass
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - comp3095_assignment

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - comp3095_assignment

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8086:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - comp3095_assignment


  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:7.9.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./docker/integrated/kafka/zookeeper_data:/var/lib/zookeeper/data
      - ./docker/integrated/kafka/zookeeper_log:/var/lib/zookeeper/log
    healthcheck:
      test: [ "CMD", "zookeeper-shell", "zookeeper:2181", "ls", "/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - comp3095_assignment

  broker:
    container_name: broker
    image: confluentinc/cp-kafka:7.9.2
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    volumes:
      - ./docker/integrated/kafka/kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - comp3095_assignment

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8089:8080"
    depends_on:
      broker:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - comp3095_assignment

  schema-registry:
    container_name: schema-registry
    hostname: schema-registry
    image: confluentinc/cp-schema-registry:7.9.2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      broker:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - comp3095_assignment



volumes:
  postgres_wellness_data:
  mongo_data:
  keycloak-data:

networks:
  comp3095_assignment:
    driver: bridge