spring.application.name=wellness-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/wellness_db
spring.datasource.username=admin
spring.datasource.password=admin


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Tables creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

wellness-service.version=v1.0

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs
