spring.application.name=api-gateway
server.port=9000

service.wellness-url=http://wellness-service:8085
service.event-url=http://event-service:8082
service.goal-url=http://goal-tracking-service:8087

service.api-gateway-authority-prefix=ROLE_

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/spring-microservices-security-realm
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=realm_access.roles
logging.level.org.springframework.security=DEBUG

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.urls[0].name=Event Service
springdoc.swagger-ui.urls[0].url=/aggregate/event-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Goal Service
springdoc.swagger-ui.urls[1].url=/aggregate/goal-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=Wellness Service
springdoc.swagger-ui.urls[2].url=/aggregate/wellness-service/v3/api-docs

services.api-gateway-fallback-url=/fallBackRoute

# Spring Actuator
# Enables health indicators for the circuit breaker
management.health.circuitbreakers.enabled=true
# makes all management endpoints accessible over the web interface
management.endpoints.web.exposure.include=*
# makes the health indicator display metrics accessible
management.endpoint.health.show-details=always

# Enables health indicator for the Circuit Breaker in Resilience4sJ
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
# Set the buffer size for storing Circuit Breaker events (analysis or logging)
resilience4j.circuitbreaker.configs.default.event-consumer-buffer-size=10
# Tracks calls based on the number of calls made, not time
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
#  Set the number of recent calls to check for success or failure
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
# Defines the failure rte threshold. IN this case the Circuit Breaker OPENS if 50% of calls fails
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
# Specifies how long the Circuit Breaker stays open before transitioning to half-open
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
# Limits the number of test calls allowed when the circuit Breaker is in HALF_OPEN state
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
# Automatically transitions the Circuit Breaker from OPEN to HALF_OPEN after the wait duration
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
# Sets the timeout duration for method executions wrapped by the TimeLimiter
resilience4j.timelimiter.configs.default.timeout-duration=3s
# Requires at least 5 calls to calculate failure-rate and decide to OPEN the Circuit Breaker
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5

# Sets maximum number times a failed call will be retired
resilience4j.retry.configs.default.max-attempts=3
# Defines how long to wait before retrying a failed call
resilience4j.retry.configs.default.wait-duration=2s
