spring.application.name=goal-tracking-service
server.port=8087

spring.data.mongodb.uri=mongodb://rootadmin:password@mongodb:27017/goal-tracking-service?authSource=admin

wellness.base-url=http://wellness-service:8085

management.endpoints.web.exposure.include=health,info

goal-service.version=v1.0

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

# Connect to broker INSIDE Docker network
spring.kafka.bootstrap-servers=broker:29092
spring.kafka.template.default-topic=goal-completed
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=http://schema-registry:8081
